#!/bin/bash

:<<'hopper-stack-notice'

Copyright 2016 Hopper-Stack

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.

hopper-stack-notice

# +------------------------------------------+
# | VARIABLES                                |
# +------------------------------------------+
source variables

useradd -d /opt/devstack -m -s /bin/bash $STACKACCOUNT -p passw0rd
echo "$STACKACCOUNT ALL=(ALL) NOPASSWD: ALL" >> /etc/sudoers
chown -R $STACKACCOUNT:$STACKACCOUNT /opt/devstack

su - $STACKACCOUNT -c "git clone https://git.openstack.org/openstack-dev/devstack"

scp variables /opt/devstack/devstack
scp create-instance /opt/devstack/devstack
chmod 755 /opt/devstack/devstack/variables
chmod 755 /opt/devstack/devstack/create-instance
cd /opt/devstack/devstack

echo "[[local|localrc]]" > local.conf
echo "HOST_IP=$THIS_SERVER_IP" >> local.conf
echo "SERVICE_HOST=$THIS_SERVER_IP" >> local.conf
echo "MYSQL_HOST=$THIS_SERVER_IP" >> local.conf
echo "RABBIT_HOST=$THIS_SERVER_IP" >> local.conf
echo "GLANCE_HOSTPORT=$THIS_SERVER_IP:9292" >> local.conf
echo "ADMIN_PASSWORD=secret" >> local.conf
echo "DATABASE_PASSWORD=secret" >> local.conf
echo "RABBIT_PASSWORD=secret" >> local.conf
echo "SERVICE_PASSWORD=secret" >> local.conf
echo "" >> local.conf
echo "# Do not use Nova-Network" >> local.conf
echo "disable_service n-net" >> local.conf
echo "# Enable Neutron" >> local.conf
echo "ENABLED_SERVICES+=,q-svc,q-dhcp,q-meta,q-agt,q-l3" >> local.conf
echo "" >> local.conf
echo "## Neutron options" >> local.conf
echo "Q_USE_SECGROUP=True" >> local.conf

FLOATRNG=`echo $THIS_SERVER_IP | cut -f1-3 -d.`
echo "FLOATING_RANGE="${FLOATRNG}.0/24"" >> local.conf
echo "FIXED_RANGE="10.0.0.0/24"" >> local.conf
echo "Q_FLOATING_ALLOCATION_POOL=start=${FLOAT_POOL_START},end=${FLOAT_POOL_END}" >> local.conf
echo "PUBLIC_NETWORK_GATEWAY="$THIS_SERVER_GATEWAY"" >> local.conf
echo "PUBLIC_INTERFACE=${PUBLIC_NIC}" >> local.conf
echo "" >> local.conf
echo "# Open vSwitch provider networking configuration" >> local.conf
echo "Q_USE_PROVIDERNET_FOR_PUBLIC=True" >> local.conf
echo "OVS_PHYSICAL_BRIDGE=br-ex" >> local.conf
echo "PUBLIC_BRIDGE=br-ex" >> local.conf
echo "OVS_BRIDGE_MAPPINGS=public:br-ex" >> local.conf

FILE=stack.sh
# echo "#!/usr/bin/env bash" > $FILE
echo "sudo iptables -I INPUT 2 -m state --state NEW -m tcp -p tcp --dport 80 -j ACCEPT" >> $FILE
echo "sudo iptables -I INPUT 2 -m state --state NEW -m tcp -p tcp --dport 6080 -j ACCEPT" >> $FILE
echo "sudo service iptables save > /dev/null 2>&1" >> $FILE
echo "sudo service iptables restart > /dev/null 2>&1" >> $FILE

echo
tput setab 4
echo -n " Perform the following "
tput rmso
tput sgr0
echo
tput setf 2
echo " su - $STACKACCOUNT"
echo " cd /opt/devstack/devstack"
echo " ./stack.sh"
tput setf 7
echo

