#!/bin/bash

:<<'hopper-stack-notice'

Copyright 2016 Hopper-Stack

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.

hopper-stack-notice

# +------------------------------------------+
# | VARIABLES                                |
# +------------------------------------------+
STACKACCOUNT=hopperadm
THIS_SERVER_IP=192.168.122.222
THIS_SERVER_GATEWAY=192.168.122.1
FLOAT_POOL_START=192.168.122.223
FLOAT_POOL_END=192.168.122.230
PUBLIC_NIC=eth1

